dashboard:
  image: adadesions/bsrumap
  ports:
   - "3000:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://localhost:27017/bsrumap
   - ROOT_URL=http://bsrumap.com

mongo:
  image: mongo:latest
